name: Build

on:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Rename APK with version
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/stealthchat_android_v${BUILD_NUMBER}.apk
       
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stealthchat-android-v${{ github.run_number }}
          path: build/app/outputs/flutter-apk/stealthchat_android_v*.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
     - name: Get dependencies
        run: flutter pub get
       
      - name: Build Windows
        run: flutter build windows --release
       
      - name: Rename Windows build with version
        run: |
          $BUILD_NUMBER = "${{ github.run_number }}"
          $OLD_PATH = "build\windows\x64\runner\Release"
          $NEW_PATH = "build\windows\x64\runner\Release_v$BUILD_NUMBER"
          Move-Item $OLD_PATH $NEW_PATH
       
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: stealthchat-windows-v${{ github.run_number }}
          path: build/windows/x64/runner/Release_v*/
